c-eg/themoviedbapi

src/main/java/info/movito/themoviedbapi/TmdbTV.java

Implementing the /tv/polular call to tmdb API. Result set should be the same as for TmdbApi.getSearch().searchTv(query, language, page);

new methods for TmdbApi.getTvSeries() for popular credits "airing today" "top rated" etc.

---

src/main/java/info/movito/themoviedbapi/AbstractTmdbApi.java
src/main/java/info/movito/themoviedbapi/TmdbApi.java
src/main/java/info/movito/themoviedbapi/TmdbConfig.java
src/main/java/info/movito/themoviedbapi/TmdbTV.java
src/main/java/info/movito/themoviedbapi/model/config/TmdbTimezones.java
src/test/java/info/movito/themoviedbapi/TimezonesApiTest.java

- class Timezones maps countries <=> timezones 
- Valid Timezones will be fetched from Web during startup like Config
- searchAiringToday(...) supports timezones
- JUnit test for Timezone validity added

New classes and methods for Timezone handling

---

src/main/java/info/movito/themoviedbapi/model/MovieDb.java

i just added a toString function

add a toString function

---

src/main/java/info/movito/themoviedbapi/TmdbAccount.java
src/main/java/info/movito/themoviedbapi/model/config/Account.java

See http://www.themoviedb.org/talk/54b06944c3a3680951000691 for a discussion

New method Account.getGravatarHash and cosmetics

---

src/main/java/info/movito/themoviedbapi/model/MovieDb.java

Tmdb gives the original language and it can be quite useful.
http://docs.themoviedb.apiary.io/#reference/movies/movieid/get

Add support for original language

---

src/test/java/info/movito/themoviedbapi/MoviesApiTest.java

added unit test to retrieve credits

fixes #52 : getCast() and getCrew() methods returning null

---

src/main/java/info/movito/themoviedbapi/TmdbTV.java
src/main/java/info/movito/themoviedbapi/model/tv/TvSeries.java

When appended, you can now get TV recommendations ( `ResultsPage<TvSeries>`) by calling `TvSeries#getRecommendations()`.

Add TV Series Recommendations.

---

src/main/java/info/movito/themoviedbapi/model/Discover.java

Just a parameter fix I found while using the lib. Gladly assist with contributions.

Fix typo of parameter name.

---

src/main/java/info/movito/themoviedbapi/TmdbPeople.java
src/main/java/info/movito/themoviedbapi/model/people/PersonCredit.java
src/test/java/info/movito/themoviedbapi/PeopleApiTest.java

Solved issue #47 by replacing the deprecated "credits" with the new "combined_credits" which includes TvSeries in addition to Movies as credits.

Replaced deprecated credit with combined_credit.

---

src/main/java/info/movito/themoviedbapi/TmdbTV.java
src/main/java/info/movito/themoviedbapi/model/people/PersonPeople.java

-Add gender to PersonPeople
-Add getImages method to TmdbTV

Add gender to PersonPeople, Add getImages method to TmdbTV

---

src/main/java/info/movito/themoviedbapi/TmdbMovies.java
src/main/java/info/movito/themoviedbapi/model/MovieDb.java
src/main/java/info/movito/themoviedbapi/model/ReleaseDate.java
src/main/java/info/movito/themoviedbapi/model/ReleaseInfo.java

Change the HTTP request to TMDb and update the mapping to accommodate the new JSON response.

add support for different release types (fixes #83)

---

src/main/java/info/movito/themoviedbapi/model/Credits.java
src/main/java/info/movito/themoviedbapi/model/ExternalIds.java
src/main/java/info/movito/themoviedbapi/model/FindResults.java
src/main/java/info/movito/themoviedbapi/model/MovieDb.java
src/main/java/info/movito/themoviedbapi/model/MovieList.java
src/main/java/info/movito/themoviedbapi/model/MovieListCreationStatus.java
src/main/java/info/movito/themoviedbapi/model/MovieTranslations.java
src/main/java/info/movito/themoviedbapi/model/ProductionCountry.java
src/main/java/info/movito/themoviedbapi/model/ReleaseDate.java
src/main/java/info/movito/themoviedbapi/model/ReleaseInfo.java
src/main/java/info/movito/themoviedbapi/model/Reviews.java
src/main/java/info/movito/themoviedbapi/model/Translation.java
src/main/java/info/movito/themoviedbapi/model/Video.java
src/main/java/info/movito/themoviedbapi/model/config/Timezone.java
src/main/java/info/movito/themoviedbapi/model/config/TokenAuthorisation.java
src/main/java/info/movito/themoviedbapi/model/config/TokenSession.java
src/main/java/info/movito/themoviedbapi/model/core/MovieKeywords.java
src/main/java/info/movito/themoviedbapi/model/core/NamedElement.java
src/main/java/info/movito/themoviedbapi/model/core/ResultsPage.java
src/main/java/info/movito/themoviedbapi/model/core/StringIdElement.java
src/main/java/info/movito/themoviedbapi/model/people/Person.java
src/main/java/info/movito/themoviedbapi/model/people/PersonCredit.java
src/main/java/info/movito/themoviedbapi/model/people/PersonCredits.java
src/main/java/info/movito/themoviedbapi/model/tv/AbstractTvElement.java
src/main/java/info/movito/themoviedbapi/model/tv/TvEpisode.java
src/main/java/info/movito/themoviedbapi/model/tv/TvSeries.java

I added the set functions to all model classes not just to them I need...
I also tried to format the code like you did but it's not really consistent.

Added set functions to all model classes.

---

src/main/java/info/movito/themoviedbapi/TmdbTV.java
src/main/java/info/movito/themoviedbapi/model/ContentRating.java
src/main/java/info/movito/themoviedbapi/model/tv/TvSeries.java
src/test/java/info/movito/themoviedbapi/SeriesApiTest.java

Added mappings for content ratings to a tv series.  Also added a UT

Add 'Content Ratings' to TvSeries

---

src/main/java/info/movito/themoviedbapi/TmdbTV.java
src/main/java/info/movito/themoviedbapi/model/people/PersonCredit.java
src/main/java/info/movito/themoviedbapi/model/people/PersonPeople.java
src/main/java/info/movito/themoviedbapi/model/tv/AbstractTvElement.java
src/test/java/info/movito/themoviedbapi/AbstractTmdbApiTest.java
src/test/java/info/movito/themoviedbapi/PeopleApiTest.java
src/test/java/info/movito/themoviedbapi/SeriesApiTest.java

Added Vote Count & Popularity to credits, Known For Department to people, and Keywords to tv shows

Added new/missing fields from the API

---

src/main/java/info/movito/themoviedbapi/TmdbMovies.java
src/main/java/info/movito/themoviedbapi/model/MovieDb.java

So that we can access recommendations from the tmdbApi through movies.

Added recommended movies method in tmdbMovies

---

src/main/java/info/movito/themoviedbapi/TmdbGenre.java
src/main/java/info/movito/themoviedbapi/TmdbMovies.java
src/main/java/info/movito/themoviedbapi/model/ExternalIds.java
src/main/java/info/movito/themoviedbapi/model/MovieDb.java
src/main/java/info/movito/themoviedbapi/model/Translation.java

Translation -> added countryCode, refactored isoCode (set deprecated for compat)
https://developers.themoviedb.org/3/movies/get-movie-external-ids
TmdbMovies -> implements externalIds
MovieDb -> implements externalIds
https://developers.themoviedb.org/3/people/get-person-external-ids
https://developers.themoviedb.org/3/movies/get-movie-external-ids
https://developers.themoviedb.org/3/tv/get-tv-external-ids
https://developers.themoviedb.org/3/tv-seasons/get-tv-season-external-ids
https://developers.themoviedb.org/3/tv-episodes/get-tv-episode-external-ids
ExternalIds -> added facebookId, instagramId, twitterId
https://developers.themoviedb.org/3/genres/get-movie-list
https://developers.themoviedb.org/3/genres/get-tv-list
Genre -> implements TV genres (set deprecated for compat)

More fixes/implementations

---

README.md

There are few open issues there regarding proguard/R8 and it's good to have the proguard rules in the readme for the users.

README update for proguard issues in release builds

---

src/main/java/info/movito/themoviedbapi/TmdbSearch.java
src/test/java/info/movito/themoviedbapi/SearchApiTest.java

Improved JavaDoc comments
Added the following parameters to the function `searchTv`:
- Integer searchYear
- String language
- boolean includeAdult
Added the following parameters to the function `searchCollection`:
- boolean includeAdult

Add APIfunctionality to TmdbSearch

---

src/main/java/info/movito/themoviedbapi/TmdbApi.java
src/main/java/info/movito/themoviedbapi/TmdbTrending.java
src/main/java/info/movito/themoviedbapi/model/core/popularperson/PopularPerson.java
src/main/java/info/movito/themoviedbapi/model/search/Multi.java
src/main/java/info/movito/themoviedbapi/model/search/MultiMovie.java
src/main/java/info/movito/themoviedbapi/model/search/MultiPerson.java
src/main/java/info/movito/themoviedbapi/model/search/MultiTvSeries.java
src/main/java/info/movito/themoviedbapi/tools/time/TimeWindow.java
src/main/java/module-info.java
src/test/java/info/movito/themoviedbapi/TmdbTrendingTest.java
src/test/java/info/movito/themoviedbapi/TmdbTvSearchTest.java
src/test/resources/api_responses/trending/all.json
src/test/resources/api_responses/trending/movies.json
src/test/resources/api_responses/trending/people.json
src/test/resources/api_responses/trending/tv.json

Trending api

---

src/main/java/info/movito/themoviedbapi/model/movies/BelongsToCollection.java
src/main/java/info/movito/themoviedbapi/model/movies/MovieDb.java
src/test/resources/api_responses/movies/details.json
src/test/resources/api_responses/movies/details_with_append_to_response.json
src/test/resources/api_responses/movies/latest.json

fix "belongs_to_collection" property mapping incorrectly
